[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "https://https://api-familia-tareas-node.onrender.com"
  status = 200
  force = true
  headers = { 
    Access-Control-Allow-Origin = "*",
    Access-Control-Allow-Credentials = "true"
  }
